version: "2"

linters:
  default: all
  disable:
    - bodyclose # Too many false positives: https://github.com/timakin/bodyclose/issues/30
    - cyclop # duplicate of gocyclo
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - lll
    - mnd
    - nlreturn
    - paralleltest
    - prealloc
    - rowserrcheck # not relevant (SQL)
    - sqlclosecheck # not relevant (SQL)
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 5
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - sloppyReassign
        - rangeValCopy
        - octalLiteral
        - hugeParam
        - paramTypeCombine # already handled by gofumpt.extra-rules
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - FIXME
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US

  exclusions:
    warn-unused: true
    presets:
      - comments
    rules:
      - linters:
          - funlen
        path: .*_test.go
      - path: types.go
        text: '(?i)the error type name .(Status|[a-z]+Response). should conform to the .XxxError. format'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
